### ISSUE TITLE
(require :jss) fails on Java 17

### ISSUE THREAD

**Issue by GOFAI** [armedbear/abcl#441]
I've installed abcl on my new M1 MacBook using homebrew, only to discover `(require :jss)` now raises the following exception:
```
CL-USER(4): (require :jss)
jssASDF could not load  because Java exception 'java.lang.reflect.InaccessibleObjectException: Unable to make public java.lang.String java.util.jar.JarFile$JarFileEntry.getName() accessible: module java.base does not "opens java.util.jar" to unnamed module @2f96847e'..
Error loading /Users/walrus/.cache/common-lisp/abcl-1.8.0-fasl43-macosx-aarch64/opt/homebrew/Cellar/abcl/1.8.0/libexec/abcl-contrib.jar/jss/invoke.abcl at line 173 (offset 14606)
```
This is with Armed Bear Common Lisp 1.8.0, Java 17.0.1 Homebrew, OpenJDK 64-Bit Server VM, on macOS 12.1 on ARM64.

Googling around, it seems that Java 17 also broke some [similar tools for other JVM languages](https://www.giters.com/bmc/classutil/issues/44). But maybe there's a simple fix, like passing `--add-opens=java.base/java.util.jar=ALL-UNNAMED` to java?

**Comment by easye** [comment]
This has been fixed in the abcl-1.8.1-dev (i.e. `master`) branch in <https://github.com/armedbear/abcl/commit/93520ea9f8fd5edfdda2888819847b3d88820ff8>.

Until abcl-1.8.1 is released, you will have to build ABCL from source to use `jss` on Java17.

**Comment by alanruttenberg** [comment]
I still have this problem too, with ABCL built on Java 17. I use the following switches when invoking java: 
```
--add-opens java.base/java.util=ALL-UNNAMED
```
